### PR TITLE
support for scala 2.12.7 with tests added

### PR DESCRIPTION
**Pull request by NikolajsCmihuns**
Hi, please review support for scala 2.12.7.
Reason of Pull request - try to use allure reporting together with scalatest for browser automation
Summary:
AllureReporter was refactored a bit.
Also fixed failing test `"it should "fire TestCaseStarted event on test case start""`

### CODE REVIEW

**Review by baev — APPROVED** [review]

**Comment by baev** [comment]
@NikolajsCmihuns thanks! Could you please link your commits with Github account?

**Comment by NikolajsCmihuns** [comment]
@baev Thank you, looks like everything ok now

**Comment by NikolajsCmihuns** [comment]
https://github.com/allure-framework/allure-scalatest/pull/20 can be closed then

**Comment by baev** [comment]
@NikolajsCmihuns thanks!

**Pull request merged**
